[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "echo 'Building with environment variables...'",
  "echo 'VITE_SUPABASE_URL='$VITE_SUPABASE_URL",
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"