name: Deploy Supabase Edge Functions and Migrations

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Apply principle of least privilege
    permissions:
      contents: read
    
    # Only run on specific branches/environments for security
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Supabase CLI
        run: |
          npm install -g supabase

      - name: Authenticate Supabase CLI
        run: |
          supabase login --access-token "${{ secrets.SUPABASE_ACCESS_TOKEN }}"

      - name: Link to Supabase Project
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Deploy Supabase Edge Functions
        run: |
          supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Run Supabase Migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          # Use Supabase CLI's built-in authentication instead of direct database access
          # This is more secure as it uses proper API authentication
          supabase db push --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
